---
- hosts: linux_server
  become: yes
  vars_files:
    - vars/vault.yml

  vars:
    samba_users:
      - { name: 'martin', group: 'it', password: "{{ vault_samba_password_martin }}" }
      - { name: 'chunga', group: 'finance', password: "{{ vault_samba_password_chunga }}" }
      - { name: 'cathy', group: 'operations', password: "{{ vault_samba_password_cathy }}" }
      - { name: 'grace', group: 'legal', password: "{{ vault_samba_password_grace }}" }


    samba_shares:
      - name: PUBLIC
        path: /srv/samba/public
        comment: "This is public share for all departments"
        guest_ok: yes
      - name: IT
        path: /srv/samba/it
        comment: "This folder is for the IT department only"
        valid_users: "@it"
        force_group: 'it'
      - name: FINANCE
        path: /srv/samba/finance
        comment: "This folder is for the Finance department only"
        valid_users: "@finance"
        force_group: 'finance'
      - name: LEGAL
        path: /srv/samba/legal
        comment: "This folder is for the Legal department only"
        valid_users: "@legal"
        force_group: 'legal'
      - name: OPERATIONS
        path: /srv/samba/operations
        comment: "This folder is for the Operations department only"
        valid_users: "@operations"
        force_group: 'operations'

    apache_modules:
      - rewrite
      - ssl
      - headers
      - proxy
      - proxy_http
      - proxy_wstunnel
      - deflate
      - expires
      - socache_shmcb

    apache_server_admin: "ansible@malawi.com"
    apache_timeout: 300
    apache_keepalive: "On"
    apache_keepalive_timeout: 5
    apache_max_keepalive_requests: 100

    apache_mpm: "event"
    apache_mpm_start_servers: 2
    apache_mpm_min_spare_threads: 25
    apache_mpm_max_spare_threads: 75
    apache_mpm_thread_limit: 64
    apache_mpm_threads_per_child: 25
    apache_mpm_max_request_workers: 150

    apache_vhosts:
      - domain: "malawi.com"
      - domain: "test.local"

  roles:
    - common
    - apache
    - samba
    - monitoring
