---


- hosts: linux_server
  become: yes
  vars:
    samba_users:
      - { name: 'martin', group: 'it', password: 'martin12345'}
      - { name: 'chunga', group: 'finance', password: 'chunga12345'}
      - { name: 'cathy', group: 'operations', password: 'cathy12345'}
      - { name: 'grace', group: 'legal', password: 'grace12345'}

    samba_shares:
      - name: PUBLIC
        path: /srv/samba/public
        comment: "This is public share for all departments"
        guest_ok: yes
      - name: IT
        path: /srv/samba/it
        comment: "This folder is for the IT department only"
        valid_users: "@it"
        force_group: 'it'
      - name: FINANCE
        path: /srv/samba/finance
        comment: "This folder is for the Finance department only"
        valid_users: "@finance"
        force_group: 'finance'
      - name: LEGAL
        path: /srv/samba/legal
        comment: "This folder is for the Legal department only"
        valid_users: "@legal"
        force_group: 'legal'
      - name: OPERATIONS
        path: /srv/samba/operations
        comment: "This folder is for the Operations department only"
        valid_users: "@operations"
        force_group: 'operations'

    apache_modules:
      - rewrite
      - ssl
      - headers
      - proxy
      - proxy_http
      - proxy_wstunnel
      - deflate
      - expires
      - socache_shmcb

  tasks:
 # - name: UPDATE REPOSITORIES
 #   apt:
 #     update_cache: yes

  - name: INSTALL APACHE2 WEB SERVER
    apt:
      name: apache2
      state: latest

  - name: ENSURE APACHE2 IS STARTED AND ENABLED
    systemd:
      name: apache2
      state: started
      enabled: true
    when: ansible_facts['os_family'] == "Debian"

  - name: ENABLE APACHE MODULES
    community.general.apache2_module:
      name: "{{ item }}"
      state: present
    loop: "{{ apache_modules }}"
    notify: RESTART APACHE

  - name: INSTALL SAMBA PACKAGE ON UBUNTU
    apt:
      name:
       - samba
       - samba-common-bin
       - smbclient
      state: latest
    when: ansible_facts['os_family'] == "Debian"

  - name: CREATE THE DEPARTMENTS GROUPS #This will create linux groups so that the "Valid users = @group" works
    group:
      name: "{{ item.force_group }}"
      state: present
    loop: "{{ samba_shares }}"
    when: item.force_group is defined

  - name: CREATE THE DIRECTORIES ON THE SERVER #This will create the actual directories on the disk
    file:
      path: "{{ item.path }}"
      state: directory
      owner: root
      group: "{{ item.force_group | default('root') }}"
      mode: '0770'
    loop: "{{ samba_shares }}"

  - name: DEPLOY THE SAMBA CONFIGURATIONS
    template:
      src: templates/smb.conf.j2
      dest: /etc/samba/smb.conf
      validate: "testparm -s %s"
    notify: RESTART SAMBA

  - name: CREATE LINUX USERS AND ADD TO GROUPS
    user:
      name: "{{ item.name }}"
      groups: "{{ item.group }}"
      append: yes
    loop: "{{ samba_users }}"

  - name: SET SAMBA PASSWORDS
    shell: "printf '{{ item.password }}\n{{ item.password }}\n' | smbpasswd -a {{ item.name }}"
    loop: "{{ samba_users }}"
    register: smbpasswd_result
    changed_when: "'Added user' in smbpasswd_result.stdout or 'Password changed' in smbpasswd_result.stdout"

  - name: ENSURE SAMBA AD SERVICE IS NOT ENABLED
    systemd:
      name: samba-ad-dc
      masked: no
      state: stopped
      enabled: no
      daemon_reload: yes

  - name: ENSURE SMB SERVICES ARE STARTED AND ENABLED
    systemd:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
      - smbd
      - nmbd

  handlers:
    - name: RESTART SAMBA
      systemd:
        name: "{{ item }}"
        state: restarted
      loop:
        - smbd
        - nmbd
    - name: RESTART APACHE
      systemd:
        name: apache2
        state: restarted
