---
- name: INSTALL SAMBA PACKAGE ON UBUNTU
  apt:
    name:
     - samba
     - samba-common-bin
     - smbclient
    state: latest
  when: ansible_facts['os_family'] == "Debian"

- name: CREATE THE DEPARTMENTS GROUPS
  group:
    name: "{{ item.force_group }}"
    state: present
  loop: "{{ samba_shares }}"
  when: item.force_group is defined

- name: CREATE THE DIRECTORIES ON THE SERVER
  file:
    path: "{{ item.path }}"
    state: directory
    owner: root
    group: "{{ item.force_group | default('root') }}"
    mode: '0770'
  loop: "{{ samba_shares }}"

- name: DEPLOY THE SAMBA CONFIGURATIONS
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    validate: "testparm -s %s"
  notify: RESTART SAMBA

- name: CREATE LINUX USERS AND ADD TO GROUPS
  user:
    name: "{{ item.name }}"
    groups: "{{ item.group }}"
    append: yes
  loop: "{{ samba_users }}"

- name: SET SAMBA PASSWORDS
  shell: "printf '{{ item.password }}\n{{ item.password }}\n' | smbpasswd -a {{ item.name }}"
  loop: "{{ samba_users }}"
  register: smbpasswd_result
  changed_when: "'Added user' in smbpasswd_result.stdout or 'Password changed' in smbpasswd_result.stdout"

- name: ENSURE SAMBA AD SERVICE IS NOT ENABLED
  systemd:
    name: samba-ad-dc
    masked: no
    state: stopped
    enabled: no
    daemon_reload: yes

- name: ENSURE SMB SERVICES ARE STARTED AND ENABLED
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - smbd
    - nmbd
